config/routes.rb
Rails.application.routes.draw do

root 'appointments#index'

  resources :appointments
  resources :doctors
  resources :patients
  devise_for :users, :controllers => { registrations: 'registrations' }

end

app/models/appointment.rb
class Appointment < ActiveRecord::Base
	belongs_to :doctor
	belongs_to :patient
end

app/controllers/appointments_controller.rb
class AppointmentsController < ApplicationController
  before_action :set_appointment, only: [:show, :edit, :update, :destroy]

  # GET /appointments
  # GET /appointments.json
  def index 
    
    if current_user.role == "Doctor"
      @doctor = (Doctor.find_by user_id: current_user.id)
      if @doctor.present? 
        @appointments = @doctor.appointments
      end
    end
  end

  # GET /appointments/1
  # GET /appointments/1.json
  def show
  end

  # GET /appointments/new
  def new
    @appointment = Appointment.new
    @doctors = Doctor.all
    @patients = Patient.all
  end

  # GET /appointments/1/edit
  def edit
    @doctors = Doctor.all
    @patients = Patient.all
  end

  # POST /appointments
  # POST /appointments.json
  def create
    @appointment = Appointment.new(appointment_params)
    @appointment.doctor_id = params[:first_name][:doctor_id].to_i
    @appointment.patient_id = params[:first_name][:patient_id].to_i
    
    respond_to do |format|
      if @appointment.save
        format.html { redirect_to @appointment, notice: 'Appointment was successfully created.' }
        format.json { render :show, status: :created, location: @appointment }
      else
        format.html { render :new }
        format.json { render json: @appointment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /appointments/1
  # PATCH/PUT /appointments/1.json
  def update
    respond_to do |format|
      if @appointment.update(appointment_params)
        format.html { redirect_to @appointment, notice: 'Appointment was successfully updated.' }
        format.json { render :show, status: :ok, location: @appointment }
      else
        format.html { render :edit }
        format.json { render json: @appointment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /appointments/1
  # DELETE /appointments/1.json
  def destroy
    @appointment.destroy
    respond_to do |format|
      format.html { redirect_to appointments_url, notice: 'Appointment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_appointment
      @appointment = Appointment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def appointment_params
      params.require(:appointment).permit(:appointment, :doctor_id, :patient_id)
    end
end

app/helpers/appointments_helper.rb
module AppointmentsHelper
end

app/views/appointments/_form.html.erb
<%= form_for(@appointment) do |f| %>
  <% if @appointment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@appointment.errors.count, "error") %> prohibited this appointment from being saved:</h2>

      <ul>
      <% @appointment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :appointment %><br>
    <%= f.datetime_select :appointment %>
  </div>
  <div class="field">
    <%= f.label :doctor %><br>
    <%#= f.text_field :doctor_id %>
    <%= collection_select(:first_name, :doctor_id, @doctors, :id, :first_name ) %>

  </div>
  <div class="field">
    <%= f.label :patient %><br>
    <%#= f.text_field :patient_id %>
     <%= collection_select(:first_name, :patient_id, @patients, :id, :first_name ) %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/appointments/edit.html.erb
<h1>Editing Appointment</h1>

<%= render 'form' %>

<%= link_to 'Show', @appointment %> |
<%= link_to 'Back', appointments_path %>

app/views/appointments/index.html.erb
<p id="notice"><%= notice %></p>
<%= current_user.role == "Doctor" %>

<h1>Listing Appointments</h1>

<table>
  <thead>
    <tr>
      <th>Appointment</th>
      <th>Doctor</th>
      <th>Patient</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% if @appointments.present? %>
      <% @appointments.each do |appointment| %>
        <tr>
          <td><%= appointment.appointment %></td>
          <td><%= Doctor.find(appointment.doctor_id).first_name %></td>
          <td><%#= Patient.find(appointment.patient_id).first_name %></td>
          <td><%= link_to 'Show', appointment %></td>
          <td><%= link_to 'Edit', edit_appointment_path(appointment) %></td>
          <td><%= link_to 'Destroy', appointment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    <% else %>
      <h1>No Appointmetns for Doctor ! </h1>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Appointment', new_appointment_path %>

app/views/appointments/new.html.erb
<h1>New Appointment</h1>

<%= render 'form' %>

<%= link_to 'Back', appointments_path %>

app/views/appointments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Appointment:</strong>
  <%= @appointment.appointment %>
</p>

<p>
  <strong>Doctor:</strong>
  <%= @appointment.doctor %>
</p>

<p>
  <strong>Patient:</strong>
  <%= @appointment.patient %>
</p>

<%= link_to 'Edit', edit_appointment_path(@appointment) %> |
<%= link_to 'Back', appointments_path %>